"""first commit

Revision ID: a99ac67b301a
Revises: 
Create Date: 2026-03-27 00:02:54.123057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99ac67b301a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('smtp', 'm365', name='emailtype'), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.String(length=10), nullable=True),
    sa.Column('smtp_security', sa.Enum('tls', 'ssl', name='smtpsecurity'), nullable=True),
    sa.Column('smtp_from', sa.String(length=255), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_pass', sa.Text(), nullable=True),
    sa.Column('m365_tenant_id', sa.String(length=255), nullable=True),
    sa.Column('m365_client_id', sa.String(length=255), nullable=True),
    sa.Column('m365_client_secret', sa.Text(), nullable=True),
    sa.Column('m365_from', sa.String(length=255), nullable=True),
    sa.Column('trigger_new', sa.Boolean(), nullable=False),
    sa.Column('trigger_assign', sa.Boolean(), nullable=False),
    sa.Column('trigger_resolve', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('critical_hours', sa.Integer(), nullable=False),
    sa.Column('high_hours', sa.Integer(), nullable=False),
    sa.Column('medium_hours', sa.Integer(), nullable=False),
    sa.Column('low_hours', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.Column('group', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('technician', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.Integer(), server_default=sa.text("nextval('ticket_number_seq')"), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('hardware', 'software', 'network', 'access', 'email', 'security', 'other', name='ticketcategory'), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='ticketpriority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'on_hold', 'resolved', 'closed', name='ticketstatus'), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('submitter_name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('asset', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('critical', 'warning', 'success', 'info', name='notificationtype'), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('ticket_timeline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('created', 'assign', 'status', 'comment', 'resolved', name='timelinetype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_timeline_ticket_id'), 'ticket_timeline', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_timeline_ticket_id'), table_name='ticket_timeline')
    op.drop_table('ticket_timeline')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('sla_config')
    op.drop_table('email_config')
    # ### end Alembic commands ###
